#pragma once

enum enumError{
	ERROR_NO,
	ERROR_ILLEGALCHAR,//出现非法字符
	ERROR_PARENTHESIS_NOT_MATCH,//括号不匹配
	ERROR_INVALID_VARNAME,//无效变量名
	ERROR_WRONG_EXPRESSION,
	ERROR_EMPTY_INPUT,
	ERROR_DIVIDE_ZERO,
	ERROR_UNDEFINED_VARIABLE,
	ERROR_ZERO_POWEROF_ZERO,
	ERROR_SUBS_NOT_EQUAL,
	ERROR_NOT_LINK_VARIABLETABLE,
	ERROR_OUTOF_DOMAIN,
	ERROR_VAR_COUNT_NOT_EQUAL_NUM_COUNT,
	ERROR_I
};