#pragma once

enum enumError{
	ERROR_NO,
	ERROR_WRONG_MATH_OPERATOR,//eOperator值错误，通常是内存跑偏引起
	ERROR_ILLEGALCHAR,//出现非法字符
	ERROR_PARENTHESIS_NOT_MATCH,//括号不匹配
	ERROR_INVALID_VARNAME,//无效变量名
	ERROR_WRONG_EXPRESSION,
	ERROR_EMPTY_INPUT,//表达式为空
	ERROR_DIVIDE_ZERO,
	ERROR_UNDEFINED_VARIABLE,
	ERROR_ZERO_POWEROF_ZERO,
	ERROR_SUBS_NOT_EQUAL,
	ERROR_NOT_LINK_VARIABLETABLE,
	ERROR_OUTOF_DOMAIN,
	ERROR_VAR_COUNT_NOT_EQUAL_NUM_COUNT,
	ERROR_I,
	ERROR_INDETERMINATE_EQUATION,
	ERROR_SINGULAR_MATRIX,
	ERROR_JACOBI_ROW_NOT_EQUAL_PHI_ROW,
	ERROR_INFINITY_SOLUTIONS,
	ERROR_OVER_DETERMINED_EQUATIONS
};